Caixa.Web/Models/EstabelecimentosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Caixa.Web.Models
{
    public class EstabelecimentosViewModel
    {
        public IList<Regioes> Regioes { get; set; }

        public Estabelecimentos Estabelecimento { get; set; }
    }
}

Caixa.Web/Controllers/AcertoController.cs
using Caixa.Web.Models;
using Caixa.Web.Report;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Caixa.Web.Controllers
{
    [Authorize]
    public class AcertoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Acerto
        public ActionResult Index()
        {
            return View(db.Acerto.Include("Estabelecimento").Include("Maquina").ToList().OrderByDescending(x => x.Id).ThenByDescending(x => x.Data));
        }

        // GET: Lancamento
        public ActionResult Lancamento()
        {
            var userName = User.Identity.GetUserName();

            var regioesVM = new RegioesViewModel();
            IList<Estabelecimentos> estabelecimentoList = new List<Estabelecimentos>();

            var regioes = db.Regioes.Where(x => x.UserName == userName).ToList();

            regioesVM.Regioes = regioes;

            foreach (var item in regioes)
            {
                var estabelecimentos = db.Estabelecimento.Include("Regiao").Include("Maquinas").Where(x => x.Regiao.Nome == item.Nome).ToList();

                foreach (var est in estabelecimentos)
                {
                    estabelecimentoList.Add(est);
                }
            }

            regioesVM.Estabelecimentos = estabelecimentoList;

            return View(regioesVM);
        }


        // GET: Acerto/Create
        public ActionResult Create(int? idEstabelecimento)
        {

            var username = User.Identity.GetUserName();
            var accountSecurity = db.Security.FirstOrDefault(a => a.UserName == username);

            if (accountSecurity != null && accountSecurity.Level == 5)
            {
                var acertoVM = new AcertoViewModel();

                acertoVM.Acerto = new Acerto() {
                    Data = DateTime.Now.Date,
                    IdEstabelecimento = idEstabelecimento.GetValueOrDefault()};

                acertoVM.Estabelecimentos = db.Estabelecimento.Where(x => x.Id == idEstabelecimento).ToList();
                acertoVM.Maquinas = db.Maquina.Where(x => x.Ativo == true && x.IdEstabelecimento == idEstabelecimento).ToList();
                acertoVM.Comissionados = db.Comissionado.Where(x => x.Bloqueado == false).ToList();

                return View(acertoVM);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Acerto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Acerto acerto)
        {
            #region View Model
            var acertoVM = new AcertoViewModel();
            acertoVM.Acerto = acerto;
            acertoVM.Estabelecimentos = db.Estabelecimento.Where(x => x.Id == acerto.IdEstabelecimento).ToList();
            acertoVM.Maquinas = db.Maquina.Where(x => x.Id == acerto.IdMaquina).ToList();
            acertoVM.Comissionados = db.Comissionado.Where(x => x.Bloqueado == false).ToList();
            #endregion

            try
            {
                if (ModelState.IsValid)
                {
                    var maquina = db.Maquina.Find(acerto.IdMaquina);
                    acerto.Maquina = maquina;

                    #region Trata DI / DS
                    if (acerto.Entrada > acerto.Maquina.DI)
                    {
                        acerto.Maquina.DI = acerto.Entrada;
                    }
                    else
                    {
                        TempData["error"] = String.Format("DI (Entrada) não pode ser menor que {0}.", acerto.Maquina.DI);
                        return View("Create", acertoVM);
                    }

                    if (acerto.Saida > acerto.Maquina.DS)
                    {
                        acerto.Maquina.DS = acerto.Saida;
                    }
                    else
                    {
                        TempData["error"] = String.Format("DS (Saída) não pode ser menor que {0}.", acerto.Maquina.DS);
                        return View("Create", acertoVM);
                    }
                    #endregion

                    #region Calculos
                    var comissao = (acerto.Entrada * acerto.Comissao) / 100;
                    acerto.Subtotal = acerto.Entrada - (acerto.Despesa + acerto.Quebra + acerto.Saida);

                    if (comissao == null)
                        comissao = 0;

                    acerto.Total = acerto.Entrada - (acerto.Despesa.GetValueOrDefault(0) + acerto.Quebra.GetValueOrDefault(0) + acerto.Saida + comissao.GetValueOrDefault(0));
                    #endregion

                    if (acerto.Total.HasValue)
                    {
                        db.Acerto.Add(acerto);
                        db.SaveChanges();
                        TempData["success"] = "Acerto lançado com sucesso!";
                    }
                    else
                    {
                        TempData["error"] = "Verifique as informações e tente novamente.";
                    }

                    return View("Create", acertoVM);
                    //return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                ModelState.AddModelError("", "Não foi possível salvar as alterações. Tente de novo, e se o problema persistir consulte o administrador do sistema.");
            }

            return View(acertoVM);
        }

        // GET: Acerto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Acerto acerto = db.Acerto.Find(id);

            if (acerto == null)
                return HttpNotFound();

            var mvm = new AcertoViewModel();
            mvm.Acerto = acerto;
            mvm.Estabelecimentos = db.Estabelecimento.Where(x => x.Ativo == true).ToList();
            mvm.Maquinas = db.Maquina.Where(x => x.Ativo == true).ToList();
            mvm.Comissionados = db.Comissionado.Where(x => x.Bloqueado == false).ToList();

            return View(mvm);
        }

        // GET: Maquinas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Acerto acerto = db.Acerto.Find(id);

            if (acerto == null)
                return HttpNotFound();

            var mvm = new AcertoViewModel();
            mvm.Acerto = acerto;
            mvm.Estabelecimentos = db.Estabelecimento.Where(x => x.Ativo == true).ToList();
            mvm.Maquinas = db.Maquina.Where(x => x.Ativo == true).ToList();
            mvm.Comissionados = db.Comissionado.Where(x => x.Bloqueado == false).ToList();

            return View(mvm);
        }

        // POST: Maquinas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AcertoViewModel acertos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(acertos.Acerto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(acertos);
        }


        // GET: Acerto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Acerto acerto = db.Acerto.Find(id);
            if (acerto == null)
            {
                return HttpNotFound();
            }
            return View(acerto);
        }

        // POST: Acerto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //validação para tratar qual usuário pode realizar exclusão
            //Salvar log de exclusão
            Acerto acerto = db.Acerto.Find(id);
            db.Acerto.Remove(acerto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Relatórios

        public FileResult BaixarPDF()
        {
            var rpt = getRelatorio();

            return File(rpt.GetOutput().GetBuffer(), "application/pdf", "Documento.pdf");
        }

        private AcertoReportViewer getRelatorio()
        {
            var rpt = new AcertoReportViewer()
            {
                BasePath = Server.MapPath("/"),
                PageTitle = "Relatório de Acerto",
                ImprimirCabecalhoPadrao = true,
                ImprimirRodapePadrao = true
            };

            return rpt;
        }

        public ActionResult Preview()
        {
            var rpt = getRelatorio();

            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        private ComprovanteAcertoReportViewer getRelatorioComprovante(int IdAcerto)
        {
            var acerto = db.Acerto.Find(IdAcerto);
            var estabelecimento = db.Estabelecimento.Find(acerto.IdEstabelecimento);
            var maquina = db.Maquina.Find(acerto.IdMaquina);

            var rpt = new ComprovanteAcertoReportViewer() {
                Author = User.Identity.GetUserName(),
                acerto = acerto,
                estabelecimento = estabelecimento,
                maquina = maquina,

Caixa.Web/Controllers/Api/EstabelecimentoController.cs
using AutoMapper;
using Caixa.Web.DTOs;
using Caixa.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Caixa.Web.Controllers.Api
{
    public class EstabelecimentoController : ApiController
    {
        ApplicationDbContext db = new ApplicationDbContext();

        //GET /api/estabelecimento
        public IEnumerable<EstabelecimentoDTO> GetEstabelecimento()
        {
            return db.Estabelecimento.ToList().Select(Mapper.Map<Estabelecimentos, EstabelecimentoDTO>);
        }

        //GET /api/estabelecimento/5
        public IHttpActionResult GetEstabelecimentos(int id)
        {
            var estabelecimento = db.Estabelecimento.Find(id);

            if (estabelecimento == null)
                return NotFound();

            return Ok(Mapper.Map<Estabelecimentos, EstabelecimentoDTO>(estabelecimento));
        }

        //POST /api/estabelecimento
        [HttpPost]
        public IHttpActionResult CreateEstabelecimentos(EstabelecimentoDTO estabelecimentosDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var estabelecimento = Mapper.Map<EstabelecimentoDTO, Estabelecimentos>(estabelecimentosDto);
            db.Estabelecimento.Add(estabelecimento);
            db.SaveChanges();

            estabelecimentosDto.Id = estabelecimento.Id;

            return Created(new Uri(Request.RequestUri + "/" + estabelecimento.Id.ToString()), estabelecimentosDto);
        }

        //PUT /api/estabelecimento/1
        [HttpPut]
        public void UpdateEstabelecimentos(int id, EstabelecimentoDTO estabelecimentosDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var estabelecimentoInDB = db.Estabelecimento.Find(id);

            if (estabelecimentoInDB == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            //AutoMapper
            Mapper.Map(estabelecimentosDto, estabelecimentoInDB);

            db.SaveChanges();
        }

        //DELETE /api/estabelecimento/1
        [HttpDelete]
        public void DeleteEstabelecimento(int id)
        {
            var estabelecimentoInDB = db.Estabelecimento.Find(id);

            if (estabelecimentoInDB == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            db.Estabelecimento.Remove(estabelecimentoInDB);
            db.SaveChanges();
        }
    }
}

Caixa.Web/Controllers/EstabelecimentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Caixa.Web.Models;
using Microsoft.AspNet.Identity;

namespace Caixa.Web.Controllers
{
    public class EstabelecimentosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Estabelecimentos
        public ActionResult Index()
        {
            var estabelecimento = db.Estabelecimento.Include("Regiao").ToList().OrderBy(a => a.Nome);
            return View(estabelecimento);
        }

        // GET: Estabelecimentos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimentos estabelecimentos = db.Estabelecimento.Find(id);
            if (estabelecimentos == null)
            {
                return HttpNotFound();
            }
            return View(estabelecimentos);
        }

        // GET: Estabelecimentos/Create
        public ActionResult Create()
        {
            var estabelecimentoVM = new EstabelecimentosViewModel();
            var userName = User.Identity.GetUserName();

            estabelecimentoVM.Estabelecimento = new Estabelecimentos() { Ativo = true, ModUser = userName };
            estabelecimentoVM.Regioes = db.Regioes.Where(x => x.UserName == userName).ToList();

            return View(estabelecimentoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Estabelecimentos estabelecimentos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    estabelecimentos.ModUser = User.Identity.GetUserName();

                    db.Estabelecimento.Add(estabelecimentos);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                ModelState.AddModelError("", "Não foi possível salvar as alterações. Tente de novo, e se o problema persistir consulte o administrador do sistema.");
            }
            return View(estabelecimentos);
        }

        // GET: Estabelecimentos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var estabelecimentoVM = new EstabelecimentosViewModel();
            var userName = User.Identity.GetUserName();

            estabelecimentoVM.Estabelecimento = db.Estabelecimento.Find(id);
            estabelecimentoVM.Regioes = db.Regioes.Where(x => x.UserName == userName).ToList();

            if (estabelecimentoVM == null)
            {
                return HttpNotFound();
            }
            return View(estabelecimentoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EstabelecimentosViewModel estabelecimentosVM)
        {
            if (ModelState.IsValid)
            {
                estabelecimentosVM.Estabelecimento.ModUser = User.Identity.GetUserName();

                db.Entry(estabelecimentosVM.Estabelecimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estabelecimentosVM);
        }

        // GET: Estabelecimentos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimentos estabelecimentos = db.Estabelecimento.Find(id);
            if (estabelecimentos == null)
            {
                return HttpNotFound();
            }
            return View(estabelecimentos);
        }

        // POST: Estabelecimentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estabelecimentos estabelecimentos = db.Estabelecimento.Find(id);
            db.Estabelecimento.Remove(estabelecimentos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult RelatorioEstabelecimentos()
        {
            var estabelecimentos = db.Estabelecimento.ToList();
            return View(estabelecimentos);
        }

        public ActionResult RelatorioAcertoEstabelecimentos()
        {
            return View();
        }
    }
}

Caixa.Web/Views/Estabelecimentos/Create.cshtml
@model Caixa.Web.Models.EstabelecimentosViewModel

@{
    ViewBag.Title = "Novo cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Adicionar novo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Estabelecimentos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.RegiaoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Estabelecimento.RegiaoId, new SelectList(Model.Regioes, "Id", "Nome", Model.Estabelecimento.RegiaoId), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Estabelecimento.RegiaoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Estabelecimento.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Estabelecimento.Ativo)
                    @Html.ValidationMessageFor(model => model.Estabelecimento.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Caixa.Web/Views/Estabelecimentos/Delete.cshtml
@model Caixa.Web.Models.Estabelecimentos

@{
    ViewBag.Title = "Excluir cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir</h2>

<h3>Você tem certeza que deseja excluir?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Estabelecimento")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Regiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Regiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Caixa.Web/Views/Estabelecimentos/Details.cshtml
@model Caixa.Web.Models.Estabelecimentos

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Estabelecimentos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Estabelecimento")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>    

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Regiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Regiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>   

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModUser)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Caixa.Web/Views/Estabelecimentos/Edit.cshtml
@model Caixa.Web.Models.EstabelecimentosViewModel

@{
    ViewBag.Title = "Editar Estabelecimento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estabelecimentos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Estabelecimento.Id)

        <div class="form-group">
            @Html.Label("Estabelecimento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estabelecimento.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.RegiaoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Estabelecimento.RegiaoId, new SelectList(Model.Regioes, "Id", "Nome", Model.Estabelecimento.RegiaoId), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Estabelecimento.RegiaoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Estabelecimento.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estabelecimento.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estabelecimento.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estabelecimento.Ativo)
                    @Html.ValidationMessageFor(model => model.Estabelecimento.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Caixa.Web/Views/Estabelecimentos/RelatorioAcertoEstabelecimentos.cshtml
<iframe width="800" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiOGZiODRhMGUtZmE4Ni00YzlhLWI5OGYtNzQ2M2Y5NDRkNjU0IiwidCI6IjE0ZTRjNjlkLTBjODgtNGJhZi1iMjFmLTM3NWFlYzk3M2ZiOCJ9" frameborder="0" allowFullScreen="true"></iframe>

Caixa.Web/Views/Estabelecimentos/RelatorioEstabelecimentos.cshtml
@model IEnumerable<Caixa.Web.Models.Estabelecimentos>

@{
    ViewBag.Title = "Relatorio de Estabelecimentos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Relatorio Estabelecimentos</h2>

    @foreach (var item in Model)
    {
        <h4>@Html.ActionLink(item.Nome, "Create", "Acerto", new { idEstabelecimento = item.Id },null)</h4>
    }