Caixa.Web/Models/MaquinaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Caixa.Web.Models
{
    public class MaquinaViewModel
    {
        public Maquinas Maquina { get; set; }

        public IList<Estabelecimentos> Estabelecimentos { get; set; }
    }
}

Caixa.Web/Models/Maquinas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Caixa.Web.Models
{
    public class Maquinas
    {
        public int Id { get; set; }

        [Index(IsUnique = true)]
        public int Codigo { get; set; }
        public string Tema { get; set; }

        [Index(IsUnique = true)]
        public int Lacre { get; set; }

        [Display(Name = "DI (Entrada)")]
        public float DI { get; set; }

        [Display(Name = "DS (Saída)")]
        public float DS { get; set; }

        [Display(Name = "Estabelecimento")]
        [ForeignKey("Estabelecimento")]
        public int IdEstabelecimento { get; set; }
        public Estabelecimentos Estabelecimento { get; set; }
        public bool Ativo { get; set; }

        [Display(Name = "Último usuário que modificou")]
        public string ModUser { get; set; }

    }
}

Caixa.Web/Controllers/MaquinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Caixa.Web.Models;
using Microsoft.AspNet.Identity;

namespace Caixa.Web.Controllers
{
    public class MaquinasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Maquinas
        public ActionResult Index()
        {
            return View(db.Maquina.Include("Estabelecimento").ToList());
        }

        // GET: Maquinas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquinas maquinas = db.Maquina.Find(id);
            if (maquinas == null)
                return HttpNotFound();

            var mvm = new MaquinaViewModel();
            mvm.Maquina = maquinas;
            mvm.Estabelecimentos = db.Estabelecimento.Where(x => x.Ativo == true).ToList();

            return View(mvm);
        }

        // GET: Maquinas/Create
        public ActionResult Create()
        {
            var mvm = new MaquinaViewModel();
            mvm.Maquina = new Maquinas() { Ativo = true };
            mvm.Estabelecimentos = db.Estabelecimento.Where(x => x.Ativo == true).ToList();
            return View(mvm);
        }

        // POST: Maquinas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MaquinaViewModel maquinas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    maquinas.Maquina.ModUser = User.Identity.GetUserName();

                    db.Maquina.Add(maquinas.Maquina);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                ModelState.AddModelError("", "Não foi possível salvar as alterações. Tente de novo, e se o problema persistir consulte o administrador do sistema.");
            }

            return View(maquinas);
        }

        // GET: Maquinas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquinas maquinas = db.Maquina.Find(id);

            if (maquinas == null)
                return HttpNotFound();

            var mvm = new MaquinaViewModel();
            mvm.Maquina = maquinas;
            mvm.Estabelecimentos = db.Estabelecimento.Where(x => x.Ativo == true).ToList();

            return View(mvm);
        }

        // POST: Maquinas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MaquinaViewModel maquinas)
        {
            if (ModelState.IsValid)
            {
                maquinas.Maquina.ModUser = User.Identity.GetUserName();

                db.Entry(maquinas.Maquina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maquinas);
        }

        // GET: Maquinas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquinas maquinas = db.Maquina.Find(id);
            if (maquinas == null)
            {
                return HttpNotFound();
            }
            return View(maquinas);
        }

        // POST: Maquinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Maquinas maquinas = db.Maquina.Find(id);
            db.Maquina.Remove(maquinas);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult RelatorioMaquinas()
        {
            return View();
        }
    }
}

Caixa.Web/Views/Maquinas/Create.cshtml
@model Caixa.Web.Models.MaquinaViewModel

@{
    ViewBag.Title = "Cadastro de Máquinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>


@using (Html.BeginForm("Create","Maquinas",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Máquinas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Tema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Tema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.DI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.DI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.DI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.DS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.DS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.DS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Lacre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Lacre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Lacre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.IdEstabelecimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Maquina.IdEstabelecimento, new SelectList(Model.Estabelecimentos, "Id", "Nome", Model.Maquina.IdEstabelecimento), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Maquina.Ativo)
                    @Html.ValidationMessageFor(model => model.Maquina.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Caixa.Web/Views/Maquinas/Delete.cshtml
@model Caixa.Web.Models.Maquinas

@{
    ViewBag.Title = "Excluir cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>

<h3>Você tem certeza que deseja excluir?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lacre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lacre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estabelecimento.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estabelecimento.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Caixa.Web/Views/Maquinas/Details.cshtml
@model Caixa.Web.Models.MaquinaViewModel

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Maquina.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.DI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.DI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.DS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.DS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.Lacre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Lacre)
        </dd>

        <dt>
           Estabelecimento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Estabelecimento.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maquina.ModUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.ModUser)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Maquina.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Caixa.Web/Views/Maquinas/Edit.cshtml
@model Caixa.Web.Models.MaquinaViewModel

@{
    ViewBag.Title = "Alterar cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Máquinas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Maquina.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Tema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Tema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.DI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.DI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.DI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.DS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.DS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.DS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Lacre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maquina.Lacre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maquina.Lacre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.IdEstabelecimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Maquina.IdEstabelecimento, new SelectList(Model.Estabelecimentos, "Id", "Nome", Model.Maquina.IdEstabelecimento), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maquina.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Maquina.Ativo)
                    @Html.ValidationMessageFor(model => model.Maquina.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Caixa.Web/Views/Maquinas/Index.cshtml
@model IEnumerable<Caixa.Web.Models.Maquinas>

@{
    ViewBag.Title = "Máquinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Máquinas</h2>

<p>
    @Html.ActionLink("Cadastrar novo", "Create", null, new { @class = "btn btn-primary" })
</p>
<table id="maquinas" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tema)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lacre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estabelecimento.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tema)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lacre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estabelecimento.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
      $(document).ready(function () {
          $('#maquinas').DataTable({
              "language": {
                  "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
              }
          });
  });
    </script>
}

Caixa.Web/Views/Maquinas/RelatorioMaquinas.cshtml
<iframe width="800" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiMDFhOTdiZmItMmRhOS00ZDVjLWI0ZjUtZDkzZjViYjI0ODc0IiwidCI6IjE0ZTRjNjlkLTBjODgtNGJhZi1iMjFmLTM3NWFlYzk3M2ZiOCJ9" frameborder="0" allowFullScreen="true"></iframe>